### ISSUE TITLE
Issues compliing the HMI Client

### ISSUE THREAD

**Issue by DVMKRSP** [ElectronicCats/tutorials#1]
Hello,

i purchased the Opta dev kit and the GigaR1 with display shield to run this code.  I am currently getting issues compiling the code for the HMI client. Any help is appreciated.

> WARNING: library ArduinoRS485 claims to run on samd, mbed_portenta, mbed_opta, mbed_nano, renesas_uno architecture(s) and may be incompatible with your current board which runs on mbed_giga architecture(s).
WARNING: library ArduinoModbus claims to run on megaavr, samd, mbed_nano, mbed_portenta, mbed_opta architecture(s) and may be incompatible with your current board which runs on mbed_giga architecture(s).
C:\Users\dv\Downloads\ElectronicCats-tutorials-v1.1_CANBusShield-4-g3568bd7\ElectronicCats-tutorials-3568bd7\HMI\HMI_Client\img_arduinologo.c:25:16: error: 'LV_IMG_CF_TRUE_COLOR' undeclared here (not in a function); did you mean 'LV_SUBJECT_TYPE_COLOR'?
   .header.cf = LV_IMG_CF_TRUE_COLOR,
                ^~~~~~~~~~~~~~~~~~~~
                LV_SUBJECT_TYPE_COLOR
C:\Users\dv\Downloads\ElectronicCats-tutorials-v1.1_CANBusShield-4-g3568bd7\ElectronicCats-tutorials-3568bd7\HMI\HMI_Client\img_arduinologo.c:26:11: error: 'lv_image_header_t {aka struct <anonymous>}' has no member named 'always_zero'
   .header.always_zero = 0,
           ^~~~~~~~~~~
C:\Users\dv\Downloads\ElectronicCats-tutorials-v1.1_CANBusShield-4-g3568bd7\ElectronicCats-tutorials-3568bd7\HMI\HMI_Client\img_arduinologo.c:27:11: error: 'lv_image_header_t {aka struct <anonymous>}' has no member named 'reserved'; did you mean 'reserved_2'?
   .header.reserved = 0,
           ^~~~~~~~
           reserved_2
C:\Users\dv\Downloads\ElectronicCats-tutorials-v1.1_CANBusShield-4-g3568bd7\ElectronicCats-tutorials-3568bd7\HMI\HMI_Client\img_arduinologo.c:30:24: error: 'LV_COLOR_SIZE' undeclared here (not in a function); did you mean 'LV_COLOR_MAKE'?
   .data_size = 30000 * LV_COLOR_SIZE / 8,
                        ^~~~~~~~~~~~~
                        LV_COLOR_MAKE
C:\Users\dv\Downloads\ElectronicCats-tutorials-v1.1_CANBusShield-4-g3568bd7\ElectronicCats-tutorials-3568bd7\HMI\HMI_Client\img_arduinologo.c:31:11: error: 'img_arduinologo_map' undeclared here (not in a function); did you mean 'img_arduinologo'?
   .data = img_arduinologo_map,
           ^~~~~~~~~~~~~~~~~~~
           img_arduinologo
C:\Users\dv\Downloads\ElectronicCats-tutorials-v1.1_CANBusShield-4-g3568bd7\ElectronicCats-tutorials-3568bd7\HMI\HMI_Client\img_error.c:1800:16: error: 'LV_IMG_CF_TRUE_COLOR' undeclared here (not in a function); did you mean 'LV_SUBJECT_TYPE_COLOR'?
   .header.cf = LV_IMG_CF_TRUE_COLOR,
                ^~~~~~~~~~~~~~~~~~~~
                LV_SUBJECT_TYPE_COLOR
C:\Users\dv\Downloads\ElectronicCats-tutorials-v1.1_CANBusShield-4-g3568bd7\ElectronicCats-tutorials-3568bd7\HMI\HMI_Client\img_error.c:1801:11: error: 'lv_image_header_t {aka struct <anonymous>}' has no member named 'always_zero'
   .header.always_zero = 0,
           ^~~~~~~~~~~
C:\Users\dv\Downloads\ElectronicCats-tutorials-v1.1_CANBusShield-4-g3568bd7\ElectronicCats-tutorials-3568bd7\HMI\HMI_Client\img_error.c:1802:11: error: 'lv_image_header_t {aka struct <anonymous>}' has no member named 'reserved'; did you mean 'reserved_2'?
   .header.reserved = 0,
           ^~~~~~~~
           reserved_2
C:\Users\dv\Downloads\ElectronicCats-tutorials-v1.1_CANBusShield-4-g3568bd7\ElectronicCats-tutorials-3568bd7\HMI\HMI_Client\img_error.c:1805:25: error: 'LV_COLOR_SIZE' undeclared here (not in a function); did you mean 'LV_COLOR_MAKE'?
   .data_size = 325600 * LV_COLOR_SIZE / 8,
                         ^~~~~~~~~~~~~
                         LV_COLOR_MAKE

exit status 1

Compilation error: 'LV_IMG_CF_TRUE_COLOR' undeclared here (not in a function); did you mean 'LV_SUBJECT_TYPE_COLOR'?

**Comment by Marcelol52** [comment]
Hi @DVMKRSP, this is due to incompatibilities between the lvgl library version and the sketch. There have been major changes to the libray since the sketch was created. You can just revert to an earlier version of the library and it should work. I just tested with version 8.3.11 and it compiled correctly. It seems like the library is getting updated to solve this issues, you can check [this post](https://forum.arduino.cc/t/giga-r1-error-message/1228337/5) on the Arduino forum for more details.
